export const technologiesData = [
    { id: 1, domain: "Frontend", name: "HTML" },
    { id: 2, domain: "Frontend", name: "CSS" },
    { id: 3, domain: "Frontend", name: "JavaScript" },
    { id: 4, domain: "Frontend", name: "React" },
    { id: 5, domain: "Frontend", name: "Vue.js" },
    { id: 6, domain: "Frontend", name: "Angular" },
    { id: 7, domain: "Frontend", name: "Svelte" },
    { id: 8, domain: "Frontend", name: "Ember.js" },
    { id: 9, domain: "Frontend", name: "Backbone.js" },
    { id: 10, domain: "Frontend", name: "jQuery" },
    { id: 11, domain: "Frontend", name: "Bootstrap" },
    { id: 12, domain: "Frontend", name: "Tailwind CSS" },
    { id: 13, domain: "Frontend", name: "Material-UI" },
    { id: 14, domain: "Frontend", name: "Semantic UI" },
    { id: 15, domain: "Frontend", name: "Foundation" },
    { id: 16, domain: "Frontend", name: "Ant Design" },
    { id: 17, domain: "Frontend", name: "Bulma" },
    { id: 18, domain: "Frontend", name: "Three.js" },
    { id: 19, domain: "Frontend", name: "D3.js" },
    { id: 20, domain: "Frontend", name: "GreenSock (GSAP)" },
    { id: 21, domain: "Frontend", name: "Framer Motion" },
    { id: 22, domain: "Frontend", name: "Styled Components" },
    { id: 23, domain: "Frontend", name: "Emotion" },
    { id: 24, domain: "Frontend", name: "Redux" },
    { id: 25, domain: "Frontend", name: "MobX" },
    { id: 26, domain: "Frontend", name: "GraphQL" },
    { id: 27, domain: "Frontend", name: "Apollo Client" },
    { id: 28, domain: "Frontend", name: "Axios" },
    { id: 29, domain: "Backend", name: "Node.js" },
    { id: 30, domain: "Backend", name: "Django" },
    { id: 31, domain: "Backend", name: "Express.js" },
    { id: 32, domain: "Backend", name: "Flask" },
    { id: 33, domain: "Backend", name: "Ruby on Rails" },
    { id: 34, domain: "Backend", name: "Spring Boot" },
    { id: 35, domain: "Backend", name: "Laravel" },
    { id: 36, domain: "Backend", name: "ASP.NET" },
    { id: 37, domain: "Backend", name: "FastAPI" },
    { id: 38, domain: "Backend", name: "Symfony" },
    { id: 39, domain: "Backend", name: "NestJS" },
    { id: 40, domain: "Backend", name: "Koa.js" },
    { id: 41, domain: "Backend", name: "Ruby on Rails" },
    { id: 42, domain: "Backend", name: "Phoenix (Elixir)" },
    { id: 43, domain: "Backend", name: "C# (.NET Core)" },
    { id: 44, domain: "Backend", name: "Golang" },
    { id: 45, domain: "Backend", name: "Scala" },
    { id: 46, domain: "Backend", name: "PHP" },
    { id: 47, domain: "Backend", name: "Java" },
    { id: 48, domain: "Backend", name: "Python" },
    { id: 49, domain: "Backend", name: "ASP.NET Core" },
    { id: 50, domain: "Backend", name: "Elixir (Phoenix)" },
    { id: 51, domain: "Backend", name: "Lumen" },
    { id: 52, domain: "Backend", name: "Slim" },
    { id: 53, domain: "Database", name: "MongoDB" },
    { id: 54, domain: "Database", name: "MySQL" },
    { id: 55, domain: "Database", name: "PostgreSQL" },
    { id: 56, domain: "Database", name: "SQLite" },
    { id: 57, domain: "Database", name: "Firebase" },
    { id: 58, domain: "Database", name: "Microsoft SQL Server" },
    { id: 59, domain: "Database", name: "Oracle" },
    { id: 60, domain: "Database", name: "Amazon RDS" },
    { id: 61, domain: "Database", name: "Cassandra" },
    { id: 62, domain: "Database", name: "Couchbase" },
    { id: 63, domain: "Database", name: "Neo4j" },
    { id: 64, domain: "Database", name: "Redis" },
    { id: 65, domain: "Database", name: "DynamoDB" },
    { id: 66, domain: "Database", name: "Elasticsearch" },
    { id: 67, domain: "Database", name: "MariaDB" },
    { id: 68, domain: "Database", name: "SQLite" },
    { id: 69, domain: "Database", name: "Memcached" },
    { id: 70, domain: "Database", name: "InfluxDB" },
    { id: 71, domain: "Database", name: "CockroachDB" },
    { id: 72, domain: "Database", name: "RethinkDB" },
    { id: 73, domain: "Other", name: "Next.js" },
    { id: 74, domain: "Other", name: "Laravel" },
    { id: 75, domain: "Other", name: "Deno" },
    { id: 76, domain: "Other", name: "Gatsby.js" },
    { id: 77, domain: "Other", name: "Nuxt.js" },
    { id: 78, domain: "Other", name: "Gulp.js" },
    { id: 79, domain: "Other", name: "NPM" },
    { id: 80, domain: "Other", name: "Yarn" },
    { id: 81, domain: "Other", name: "Webpack" },
    { id: 82, domain: "Other", name: "Rollup" },
    { id: 83, domain: "Other", name: "Parcel" },
    { id: 84, domain: "Other", name: "Babel" },
    { id: 85, domain: "Other", name: "TypeScript" },
    { id: 86, domain: "Other", name: "ESLint" },
    { id: 87, domain: "Other", name: "Prettier" },
    { id: 88, domain: "Other", name: "Jest" },
    { id: 89, domain: "Other", name: "Mocha" },
    { id: 90, domain: "Other", name: "Cypress" },
    { id: 91, domain: "Other", name: "Selenium" },
    { id: 92, domain: "Other", name: "PHPUnit" },
    { id: 93, domain: "Other", name: "Jest" },
    { id: 94, domain: "Other", name: "Mocha" },
    { id: 95, domain: "Other", name: "Cypress" },
    { id: 96, domain: "Other", name: "Selenium" },
    { id: 97, domain: "Other", name: "PHPUnit" },
    { id: 98, domain: "Other", name: "Karma" },
    { id: 99, domain: "Other", name: "Protractor" },
    { id: 100, domain: "Other", name: "TestNG" },
    { id: 101, domain: "Other", name: "Robot Framework" },
    { id: 102, domain: "Other", name: "Appium" },
    { id: 103, domain: "Other", name: "SoapUI" },
    { id: 104, domain: "Other", name: "Jasmine" },
    { id: 105, domain: "Other", name: "Behave" },
    { id: 106, domain: "Other", name: "PyTest" },
    { id: 107, domain: "Other", name: "Cucumber" },
    { id: 108, domain: "Other", name: "Gauge" },
    { id: 109, domain: "Other", name: "Jest" },
    { id: 110, domain: "Other", name: "Enzyme" },
    { id: 111, domain: "Other", name: "AVA" },
    { id: 112, domain: "Other", name: "RSpec" },
    { id: 113, domain: "Other", name: "Docker" },
    { id: 114, domain: "Other", name: "Kubernetes" },
    { id: 115, domain: "Other", name: "Jenkins" },
    { id: 116, domain: "Other", name: "Ansible" },
    { id: 117, domain: "Other", name: "Terraform" },
    { id: 118, domain: "Other", name: "Vagrant" },
    { id: 119, domain: "Other", name: "Puppet" },
    { id: 120, domain: "Other", name: "Chef" },
    { id: 121, domain: "Other", name: "GitLab CI/CD" },
    { id: 122, domain: "Other", name: "Travis CI" },
    { id: 123, domain: "Other", name: "CircleCI" },
    { id: 124, domain: "Other", name: "GitHub Actions" },
    { id: 125, domain: "Other", name: "AWS CodePipeline" },
    { id: 126, domain: "Other", name: "Azure DevOps" },
    { id: 127, domain: "Other", name: "Google Cloud Build" },
    { id: 128, domain: "Other", name: "Docker Swarm" },
    { id: 129, domain: "Other", name: "Rancher" },
    { id: 130, domain: "Other", name: "Helm" },
    { id: 131, domain: "Other", name: "Spinnaker" },
    { id: 132, domain: "Other", name: "Prometheus" }
 ];

 export const technologyNames = [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Vue.js",
      "Angular",
      "Svelte",
      "Ember.js",
      "Backbone.js",
      "jQuery",
      "Bootstrap",
      "Tailwind CSS",
      "Material-UI",
      "Semantic UI",
      "Foundation",
      "Ant Design",
      "Bulma",
      "Three.js",
      "D3.js",
      "GreenSock (GSAP)",
      "Framer Motion",
      "Styled Components",
      "Emotion",
      "Redux",
      "MobX",
      "GraphQL",
      "Apollo Client",
      "Axios",
      "Node.js",
      "Django",
      "Express.js",
      "Flask",
      "Ruby on Rails",
      "Spring Boot",
      "Laravel",
      "ASP.NET",
      "FastAPI",
      "Symfony",
      "NestJS",
      "Koa.js",
      "Phoenix (Elixir)",
      "C# (.NET Core)",
      "Golang",
      "Scala",
      "PHP",
      "Java",
      "Python",
      "ASP.NET Core",
      "Elixir (Phoenix)",
      "Lumen",
      "Slim",
      "MongoDB",
      "MySQL",
      "PostgreSQL",
      "SQLite",
      "Firebase",
      "Microsoft SQL Server",
      "Oracle",
      "Amazon RDS",
      "Cassandra",
      "Couchbase",
      "Neo4j",
      "Redis",
      "DynamoDB",
      "Elasticsearch",
      "MariaDB",
      "Memcached",
      "InfluxDB",
      "CockroachDB",
      "RethinkDB",
      "Next.js",
      "Laravel",
      "Deno",
      "Gatsby.js",
      "Nuxt.js",
      "Gulp.js",
      "NPM",
      "Yarn",
      "Webpack",
      "Rollup",
      "Parcel",
      "Babel",
      "TypeScript",
      "ESLint",
      "Prettier",
      "Jest",
      "Mocha",
      "Cypress",
      "Selenium",
      "PHPUnit",
      "Karma",
      "Protractor",
      "TestNG",
      "Robot Framework",
      "Appium",
      "SoapUI",
      "Jasmine",
      "Behave",
      "PyTest",
      "Cucumber",
      "Gauge",
      "Jest",
      "Enzyme",
      "AVA",
      "RSpec",
      "Docker",
      "Kubernetes",
      "Jenkins",
      "Ansible",
      "Terraform",
      "Vagrant",
      "Puppet",
      "Chef",
      "GitLab CI/CD",
      "Travis CI",
      "CircleCI",
      "GitHub Actions",
      "AWS CodePipeline",
      "Azure DevOps",
      "Google Cloud Build",
      "Docker Swarm",
      "Rancher",
      "Helm",
      "Spinnaker",
      "Prometheus"
    ];

    export const institutes = [
      // IITs
      "Indian Institute of Technology (IIT), Kharagpur",
      "Indian Institute of Technology (IIT), Bombay",
      "Indian Institute of Technology (IIT), Madras",
      "Indian Institute of Technology (IIT), Kanpur",
      "Indian Institute of Technology (IIT), Delhi",
      "Indian Institute of Technology (IIT), Guwahati",
      "Indian Institute of Technology (IIT), Roorkee",
      "Indian Institute of Technology (IIT), Ropar",
      "Indian Institute of Technology (IIT), Bhubaneswar",
      "Indian Institute of Technology (IIT), Gandhinagar",
      "Indian Institute of Technology (IIT), Hyderabad",
      "Indian Institute of Technology (IIT), Jodhpur",
      "Indian Institute of Technology (IIT), Patna",
      "Indian Institute of Technology (IIT), Indore",
      "Indian Institute of Technology (IIT), Mandi",
      "Indian Institute of Technology (IIT), Varanasi (Banaras Hindu University)",
      "Indian Institute of Technology (IIT), Palakkad",
      "Indian Institute of Technology (IIT), Tirupati",
      "Indian Institute of Technology (IIT), Dhanbad",
      "Indian Institute of Technology (IIT), Bhilai",
      "Indian Institute of Technology (IIT), Goa",
      "Indian Institute of Technology (IIT), Jammu",
      "Indian Institute of Technology (IIT), Dharwad",
      // NITs
      "National Institute of Technology (NIT), Tiruchirappalli (NIT Trichy)",
      "National Institute of Technology (NIT), Warangal (NIT Warangal)",
      "National Institute of Technology (NIT), Surathkal (NIT Surathkal)",
      "National Institute of Technology (NIT), Calicut (NIT Calicut)",
      "National Institute of Technology (NIT), Rourkela (NIT Rourkela)",
      "National Institute of Technology (NIT), Kurukshetra (NIT Kurukshetra)",
      "National Institute of Technology (NIT), Durgapur (NIT Durgapur)",
      "National Institute of Technology (NIT), Silchar (NIT Silchar)",
      "National Institute of Technology (NIT), Jaipur (MNIT Jaipur)",
      "National Institute of Technology (NIT), Jamshedpur (NIT Jamshedpur)",
      "National Institute of Technology (NIT), Hamirpur (NIT Hamirpur)",
      "National Institute of Technology (NIT), Jalandhar (NIT Jalandhar)",
      "National Institute of Technology (NIT), Agartala (NIT Agartala)",
      "National Institute of Technology (NIT), Patna (NIT Patna)",
      "National Institute of Technology (NIT), Raipur (NIT Raipur)",
      "National Institute of Technology (NIT), Srinagar (NIT Srinagar)",
      "National Institute of Technology (NIT), Surat (SVNIT Surat)",
      "National Institute of Technology (NIT), Nagpur (VNIT Nagpur)",
      "National Institute of Technology (NIT), Allahabad (MNNIT Allahabad)",
      "National Institute of Technology (NIT), Bhopal (MANIT Bhopal)",
      "National Institute of Technology (NIT), Goa (NIT Goa)",
      "National Institute of Technology (NIT), Meghalaya (NIT Meghalaya)",
      "National Institute of Technology (NIT), Manipur (NIT Manipur)",
      "National Institute of Technology (NIT), Mizoram (NIT Mizoram)",
      "National Institute of Technology (NIT), Nagaland (NIT Nagaland)",
      "National Institute of Technology (NIT), Puducherry (NIT Puducherry)",
      "National Institute of Technology (NIT), Arunachal Pradesh (NIT Arunachal Pradesh)",
      "National Institute of Technology (NIT), Sikkim (NIT Sikkim)",
      "National Institute of Technology (NIT), Uttarakhand (NIT Uttarakhand)",
      "National Institute of Technology (NIT), Delhi (NIT Delhi)",
      "National Institute of Technology (NIT), Andhra Pradesh (NIT Andhra Pradesh)",
      "National Institute of Technology (NIT), Manipur (NIT Manipur)",
      // Other Engineering Colleges
      "Birla Institute of Technology and Science (BITS), Pilani",
      "Vellore Institute of Technology (VIT), Vellore",
      "Manipal Institute of Technology (MIT), Manipal",
      "SRM Institute of Science and Technology (SRMIST), Chennai",
      "Amity University, Noida",
      "Thapar Institute of Engineering and Technology, Patiala",
      "PSG College of Technology, Coimbatore",
      "RV College of Engineering (RVCE), Bangalore",
      "BMS College of Engineering, Bangalore",
      "SSN College of Engineering, Chennai",
      "PES University, Bangalore",
      "Sathyabama Institute of Science and Technology, Chennai",
      "SR Engineering College (SREC), Warangal",
      "Kalinga Institute of Industrial Technology (KIIT), Bhubaneswar",
      "Lovely Professional University (LPU), Phagwara",
      "Ramaiah Institute of Technology (MSRIT), Bangalore",
      "Galgotias College of Engineering and Technology, Greater Noida",
      "Chandigarh University, Chandigarh",
      "Jain University, Bangalore",
     
  
   "NMIMS Mukesh Patel School of Technology Management and Engineering, Mumbai",
  
      "Veermata Jijabai Technological Institute (VJTI), Mumbai",
      "KJ Somaiya College of Engineering, Mumbai",
      "Sardar Patel Institute of Technology (SPIT), Mumbai",
      "Fr. C. Rodrigues Institute of Technology (Fr. CRCE), Mumbai",
      "Ramrao Adik Institute of Technology (RAIT), Mumbai",
      "Dwarkadas J. Sanghvi College of Engineering (DJ Sanghvi), Mumbai",
     
      "College of Engineering, Pune (COEP)",
      "Pimpri Chinchwad College of Engineering (PCCOE), Pune",
      "Vishwakarma Institute of Technology (VIT), Pune",
      "Sinhgad College of Engineering, Pune",
      "Army Institute of Technology (AIT), Pune",
      "MIT Academy of Engineering, Pune",
      
      "Visvesvaraya National Institute of Technology (VNIT), Nagpur",
      "Government College of Engineering, Nagpur",
      "Yeshwantrao Chavan College of Engineering (YCCE), Nagpur",
      "Anjuman College of Engineering and Technology (ACET), Nagpur",
      "Guru Nanak Institute of Engineering and Technology (GNIET), Nagpur",
      // Engineering Colleges in Aurangabad
      "Government College of Engineering, Aurangabad",
      "Mahatma Gandhi Mission's College of Engineering and Technology, Aurangabad",
      "Dr. Babasaheb Ambedkar Marathwada University (BAMU) College of Engineering, Aurangabad",
      "Marathwada Institute of Technology (MIT), Aurangabad",
      // Engineering Colleges in Amravati
      "Government College of Engineering, Amravati",
      "Sipna College of Engineering and Technology, Amravati",
      "P. R. Patil College of Engineering and Technology, Amravati",
      "Prof. Ram Meghe College of Engineering and Management, Amravati",
  ];