
 export const technologiesData = [
   { id: 1, domain: "Frontend", name: "HTML" },
   { id: 2, domain: "Frontend", name: "CSS" },
   { id: 3, domain: "Frontend", name: "JavaScript" },
   { id: 4, domain: "Frontend", name: "React" },
   { id: 5, domain: "Frontend", name: "Vue.js" },
   { id: 6, domain: "Frontend", name: "Angular" },
   { id: 7, domain: "Frontend", name: "Backbone.js" },
   { id: 8, domain: "Frontend", name: "jQuery" },
   { id: 9, domain: "Frontend", name: "Bootstrap" },
   { id: 10, domain: "Frontend", name: "Tailwind CSS" },
   { id: 11, domain: "Frontend", name: "Semantic UI" },
   { id: 12, domain: "Frontend", name: "Foundation" },
   { id: 13, domain: "Frontend", name: "Redux" },
   { id: 14, domain: "Frontend", name: "NPM" },
   { id: 15, domain: "Frontend", name: "Yarn" },
   { id: 16, domain: "Frontend", name: "TypeScript" },
   { id: 17, domain: "Frontend", name: "Selenium" },
   { id: 18, domain: "Frontend", name: "PHPUnit" },
   { id: 19, domain: "Frontend", name: "TestNG" },
   { id: 20, domain: "Frontend", name: "Robot Framework" },
   { id: 21, domain: "Frontend", name: "Docker" },
   { id: 22, domain: "Frontend", name: "Kubernetes" },
   { id: 23, domain: "Frontend", name: "GitLab CI/CD" },
   { id: 24, domain: "Frontend", name: "GitHub Actions" },
   { id: 25, domain: "Frontend", name: "AWS CodePipeline" },
   { id: 26, domain: "Frontend", name: "Azure DevOps" },
   { id: 27, domain: "Frontend", name: "Google Cloud Build" },
   { id: 28, domain: "Frontend", name: "Docker Swarm" },
   { id: 29, domain: "Backend", name: "GraphQL" },
   { id: 30, domain: "Backend", name: "Apollo Client" },
   { id: 31, domain: "Backend", name: "Axios" },
   { id: 32, domain: "Backend", name: "Node.js" },
   { id: 33, domain: "Backend", name: "Django" },
   { id: 34, domain: "Backend", name: "Express.js" },
   { id: 35, domain: "Backend", name: "Flask" },
   { id: 36, domain: "Backend", name: "Ruby on Rails" },
   { id: 37, domain: "Backend", name: "Spring Boot" },
   { id: 38, domain: "Backend", name: "ASP.NET" },
   { id: 39, domain: "Backend", name: "C# (.NET Core)" },
   { id: 40, domain: "Backend", name: "PHP" },
   { id: 41, domain: "Backend", name: "Java" },
   { id: 42, domain: "Backend", name: "Python" },
   { id: 43, domain: "Backend", name: "ASP.NET Core" },
   { id: 44, domain: "Backend", name: "MongoDB" },
   { id: 45, domain: "Backend", name: "MySQL" },
   { id: 46, domain: "Backend", name: "PostgreSQL" },
   { id: 47, domain: "Backend", name: "SQLite" },
   { id: 48, domain: "Backend", name: "Firebase" },
   { id: 49, domain: "Backend", name: "Microsoft SQL Server" },
   { id: 50, domain: "Backend", name: "Oracle" },
   { id: 51, domain: "Backend", name: "Amazon RDS" },
   { id: 52, domain: "Backend", name: "Cassandra" },
   { id: 53, domain: "Backend", name: "DynamoDB" },
   { id: 54, domain: "Backend", name: "MariaDB" },
   { id: 55, domain: "Other", name: "Next.js" }
];


 export const technologyNames = [
   // Frontend Technologies
   "HTML",
   "CSS",
   "JavaScript",
   "React",
   "Vue.js",
   "Angular",
   "Backbone.js",
   "jQuery",
   "Bootstrap",
   "Tailwind CSS",
   "Semantic UI",
   "Foundation",
   "Redux",
   "NPM",
   "Yarn",
   "TypeScript",
   "Selenium",
   "PHPUnit",
   "TestNG",
   "Robot Framework",
   "Docker",
   "Kubernetes",
   "GitLab CI/CD",
   "GitHub Actions",
   "AWS CodePipeline",
   "Azure DevOps",
   "Google Cloud Build",
   "Docker Swarm",
   // Backend Technologies
   "GraphQL",
   "Apollo Client",
   "Axios",
   "Node.js",
   "Django",
   "Express.js",
   "Flask",
   "Ruby on Rails",
   "Spring Boot",
   "ASP.NET",
   "C# (.NET Core)",
   "PHP",
   "Java",
   "Python",
   "ASP.NET Core",
   "MongoDB",
   "MySQL",
   "PostgreSQL",
   "SQLite",
   "Firebase",
   "Microsoft SQL Server",
   "Oracle",
   "Amazon RDS",
   "Cassandra",
   "DynamoDB",
   "MariaDB",
   "Next.js"
  ];
  

    export const institutes = [
      // IITs
      "IIT, Kharagpur",
      "IIT, Bombay",
      "IIT, Madras",
      "IIT, Kanpur",
      "IIT, Delhi",
      "IIT, Guwahati",
      "IIT, Roorkee",
      "IIT, Ropar",
      "IIT, Bhubaneswar",
      "IIT, Gandhinagar",
      "IIT, Hyderabad",
      "IIT, Jodhpur",
      "IIT, Patna",
      "IIT, Indore",
      "IIT, Mandi",
      "IIT, Varanasi",
      "IIT, Palakkad",
      "IIT, Goa",
      "IIT, Jammu",

      // NITs
      "NIT, Tiruchirappalli",
      "NIT, Warangal",
      "NIT, Surathkal",
      "NIT, Calicut",
      "NIT, Rourkela",
      "NIT, Kurukshetra",
      "NIT, Silchar",
      "NIT, Jaipur",
      "NIT, Jalandhar",
      "NIT, Patna",
      "NIT, Raipur",
      "NIT, Surat",
      "NIT, Nagpur (VNIT Nagpur)",
      "NIT, Allahabad (MNNIT Allahabad)",
      "NIT, Bhopal (MANIT Bhopal)",
      "NIT, Goa",
      "NIT, Meghalaya",
      "NIT, Manipur",
      "NIT, Mizoram",
      "NIT, Nagaland",
      "NIT, Delhi",
      // Other Engineering Colleges
      "BITS,Pilani",
      "VIT, Vellore",
      "MIT, Manipal",
      "SRMIST, Chennai",
      "Amity University, Noida",

      "SSN , Chennai",
      "LPU, Phagwara",
      "Chandigarh University, Chandigarh",
      "Jain University, Bangalore",
       "NMIMS , Mumbai",
      "VJTI, Mumbai",
      "KJ Somaiya, Mumbai",
      "SPIT, Mumbai",
      "DJ Sanghvi, Mumbai",
      "COEP, Pune",
      "PCCOE, Pune",
      "VIT, Pune",
      "Sinhgad College of Engineering, Pune",
      "AIT, Pune",
      "MIT , Pune",
      "VNIT, Nagpur",
      "YCCE, Nagpur",
      "VJTI, Aurangabad",
      "MIT, Aurangabad",
  ];